### ISSUE TITLE
Can you provide steps to execute. I am not able to see the result after running streamlit app.py it opens up a blank tab in localhost:8501 

### ISSUE THREAD

**Issue by Sumukh0512** [ankitajaiswal00/Try-First#4]
![image](https://user-images.githubusercontent.com/31795364/119983668-1459b380-bfde-11eb-9d47-724a4125401c.png)

**Comment by ankitajaiswal00** [comment]
Hi there, we were using streamlit when our team member was working on the website. After that, all the further implementations and new features were added on the flask file to have compatibility with the localhost website!

Check if changing the paths (from where the streamlit file is importing the other modules) works. This should work because all the frameworks and libraries are having the same version since we first made this project.

**Comment by Sumukh0512** [comment]
@ankitajaiswal00  Can you share the screenshot of your project's virtual environment installed packages list with versions like the screenshot of pip list or conda list.

**Comment by Sumukh0512** [comment]
![image](https://user-images.githubusercontent.com/31795364/120060331-d8bdf880-c074-11eb-9af7-94eccc7027b2.png)
This is my conda environment list of installed libraries. Can you tell me if i am wrong with version installations.

**Comment by kajal2111** [comment]
@Sumukh0512  hey!! i am having the same issue. please help me if you resolved that problem.

**Comment by kajal2111** [comment]
@ankitajaiswal00  can you please share the working source code in a zip file in this repo otherwise tell me in which files i have to update the paths

**Comment by ankitajaiswal00** [comment]
[tree.txt](https://github.com/ankitajaiswal00/Try-First/files/6565019/tree.txt)


This is how the tree structure of the directory looks.
Also, I have this set up on a virtual env and advise the same to run.

**Comment by ankitajaiswal00** [comment]
> ![image](https://user-images.githubusercontent.com/31795364/120060331-d8bdf880-c074-11eb-9af7-94eccc7027b2.png)
> This is my conda environment list of installed libraries. Can you tell me if i am having incompatible versions .

Please refer requirement.txt. also once try virtual env in ubuntu.

**Comment by Sumukh0512** [comment]
For the streamlit run app_streamlit.py, I am getting the output
