### ISSUE TITLE
some folders are missing in this code 

### ISSUE THREAD

**Issue by kajal2111** [ankitajaiswal00/Try-First#5]
Please send me zip file of code here ==> kajalthoke21@gmail.com 
when i download the zip file of this code i found that some files are missing so please send me.

**Comment by ankitajaiswal00** [comment]
please see this one [here](https://github.com/ankitajaiswal00/Try-First/issues/4#issuecomment-850863295).

**Comment by ankitajaiswal00** [comment]
Please check them now.
