### ISSUE TITLE
I got an Error

### ISSUE THREAD

**Issue by kajal2111** [ankitajaiswal00/Try-First#6]
when i upload any picture for try on i got this error ==>
![Screenshot 2021-06-05 152642](https://user-images.githubusercontent.com/58783985/120887957-72f0e400-c613-11eb-89b1-31c175f222f1.png)
![image](https://user-images.githubusercontent.com/58783985/120887996-a2075580-c613-11eb-92c1-0ec0cb12002c.png)

@ankitajaiswal00 please tell me how can I solve this error

**Comment by ankitajaiswal00** [comment]
This error page is generally showed up when something is wrong with the flask main.py file. But please try executing the "main.py" file. Not the other main5/,ain7 versions.

**Comment by kajal2111** [comment]
New error ==> when i upload any picture for try on i got this new error ==>
![Screenshot 2021-06-06 173555](https://user-images.githubusercontent.com/58783985/120923749-c33c7480-c6ed-11eb-9969-528483a5dd20.png)
how can I solve it?

**Comment by ankitajaiswal00** [comment]
There should be some version problem. It works fine in my system.

**Comment by Sumukh0512** [comment]
> New error ==> when i upload any picture for try on i got this new error ==>
> ![Screenshot 2021-06-06 173555](https://user-images.githubusercontent.com/58783985/120923749-c33c7480-c6ed-11eb-9969-528483a5dd20.png)
> how can I solve it?



> New error ==> when i upload any picture for try on i got this new error ==>
> ![Screenshot 2021-06-06 173555](https://user-images.githubusercontent.com/58783985/120923749-c33c7480-c6ed-11eb-9969-528483a5dd20.png)
> how can I solve it?
Even i got the same and figured it out,
You have to give correct path for frame = cv2.imread("static/Database/val/person/"+person_name+".jpg") line number 10 in person_parser.py
